// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTextSplit from '@/components/sections/about/AboutTextSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
            <SectionErrorBoundary name="about">
              <AboutTextSplit
                title="Redefining Dental Branding"
                descriptions={[
                  "At DentaPro, we understand that a dental website is the digital face of your clinic. It is where trust is established before the first appointment is ever made.",              "Our designs prioritize user experience, patient conversion, and medical authority, ensuring your practice stands out in a competitive market."]}
                textAnimation="slide-up"
              />
            </SectionErrorBoundary>
          </div>
  );
}
