// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
            <SectionErrorBoundary name="contact">
              <ContactCta
                tag="READY TO GROW?"
                text="Start your journey toward a world-class dental website today. Book a free consultation."
                primaryButton={{ text: "Book Free Consultation", href: "#" }}
                secondaryButton={{ text: "WhatsApp Us", href: "#" }}
                textAnimation="fade"
              />
            </SectionErrorBoundary>
          </div>
  );
}
