// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSplitMedia from '@/components/sections/faq/FaqSplitMedia';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
            <SectionErrorBoundary name="faq">
              <FaqSplitMedia
                tag="SUPPORT"
                title="Frequently Asked Questions"
                description="Common questions regarding our process and dental web services."
                items={[
                  { question: "How long does a website build take?", answer: "Typically 4-6 weeks depending on project complexity." },
                  { question: "Do you provide hosting?", answer: "Yes, we offer premium, secure, and fast hosting solutions." },
                  { question: "Do you specialize in Dental SEO?", answer: "Absolutely. We dominate local SEO and Google Maps for clinics." },
                  { question: "Can I integrate my booking software?", answer: "We integrate with all major dental software providers." }
                ]}
                imageSrc="http://img.b2bpic.net/free-photo/young-female-dentist-showing-patient-dental-xray-dentistry-concept_169016-67117.jpg"
                textAnimation="slide-up"
              />
            </SectionErrorBoundary>
          </div>
  );
}
