// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroSplitVerticalMarqueeTall from '@/components/sections/hero/HeroSplitVerticalMarqueeTall';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
            <SectionErrorBoundary name="hero">
              <HeroSplitVerticalMarqueeTall
                tag="PREMIUM DENTAL AGENCY"
                title="Websites That Build Trust and Convert Patients"
                description="We specialize in high-end web solutions for modern dental practices, combining luxury aesthetics with conversion-focused performance."
                primaryButton={{
                  text: "Book a Free Consultation",              href: "#contact"}}
                secondaryButton={{
                  text: "View Our Portfolio",              href: "#portfolio"}}
                leftItems={[
                  { imageSrc: "http://img.b2bpic.net/free-photo/nobody-waiting-room-with-front-desk-reception-wall-screen-tv-with-promotional-offer-private-practice-hopital-waiting-area-patients-with-doctor-appointments-modern-healthcare-clinic_482257-46743.jpg" },
                  { imageSrc: "http://img.b2bpic.net/free-photo/clinic-oral-hospital-adult-open_1303-340.jpg" },
                  { imageSrc: "http://img.b2bpic.net/free-photo/young-female-dentist-showing-patient-dental-xray-dentistry-concept_169016-67233.jpg" }
                ]}
                rightItems={[
                  { imageSrc: "http://img.b2bpic.net/free-photo/still-life-graphic-design-studio_23-2151320712.jpg" },
                  { imageSrc: "http://img.b2bpic.net/free-photo/portrait-young-beautiful-woman-smiling_58466-12186.jpg" },
                  { imageSrc: "http://img.b2bpic.net/free-photo/equipment-dental-instruments-dentist-s-office-tools-close-up_8353-1674.jpg" }
                ]}
                textAnimation="fade-blur"
              />
            </SectionErrorBoundary>
          </div>
  );
}
