// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsFeatureCards from '@/components/sections/metrics/MetricsFeatureCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
            <SectionErrorBoundary name="metrics">
              <MetricsFeatureCards
                tag="PERFORMANCE"
                title="Data-Driven Success"
                description="We don't just design websites; we drive tangible results for your practice."
                metrics={[
                  { value: "45%", title: "Average Increase in Bookings", features: ["Patient-focused UX", "Faster conversion path", "Optimized mobile flow"] },
                  { value: "98%", title: "Performance Score", features: ["Optimized images", "Efficient codebase", "Fast page loads"] },
                  { value: "120+", title: "Successful Launches", features: ["Dental clinics", "Orthodontists", "Oral Surgeons"] }
                ]}
                textAnimation="slide-up"
              />
            </SectionErrorBoundary>
          </div>
  );
}
