// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "portfolio" section.

import React from 'react';
import FeaturesTaggedCards from '@/components/sections/features/FeaturesTaggedCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function PortfolioSection(): React.JSX.Element {
  return (
    <div id="portfolio" data-section="portfolio">
            <SectionErrorBoundary name="portfolio">
              <FeaturesTaggedCards
                tag="LATEST WORK"
                title="Excellence in Dental Design"
                description="Explore our recent projects and witness the DentaPro standard of quality."
                items={[
                  { tag: "Cosmetic", title: "SmileCraft Clinic", description: "High-end aesthetic clinic website.", imageSrc: "http://img.b2bpic.net/free-photo/homepage-seen-laptop-screen_23-2149416731.jpg", primaryButton: { text: "View Case Study", href: "#" } },
                  { tag: "Surgery", title: "Maxilla Pro", description: "Surgical expertise landing page.", imageSrc: "http://img.b2bpic.net/free-photo/female-patient-receiving-dental-treatment_107420-65420.jpg", primaryButton: { text: "View Case Study", href: "#" } },
                  { tag: "General", title: "Gentle Care Dental", description: "Family-focused modern dental hub.", imageSrc: "http://img.b2bpic.net/free-photo/empty-hotel-lounge-with-cozy-furniture_482257-67425.jpg", primaryButton: { text: "View Case Study", href: "#" } }
                ]}
                textAnimation="slide-up"
              />
            </SectionErrorBoundary>
          </div>
  );
}
