// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
            <SectionErrorBoundary name="services">
              <FeaturesRevealCardsBento
                tag="SERVICES"
                title="Comprehensive Dental Web Solutions"
                description="From custom web design to appointment booking integration, we handle everything your practice needs to grow."
                items={[
                  { title: "Dental Web Design", description: "Custom, luxurious website design tailored for dental practices.", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/stylish-beautiful-spacious-dental-clinic_8353-9586.jpg" },
                  { title: "Cosmetic Dentistry", description: "Websites that highlight your cosmetic transformation services.", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/they-always-everything-same-time_329181-10706.jpg" },
                  { title: "SEO Strategy", description: "Dominating local search and Google Maps results.", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/smiling-dentist-wearing-surgical-gloves_107420-74190.jpg" },
                  { title: "Booking Systems", description: "Seamless integration with your appointment software.", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/orthodontist-using-horizontal-green-screen-tablet-oral-care-dentistry-woman-working-as-dentist-with-chroma-key-isolated-mockup-template-while-looking-teeth-scan_482257-28427.jpg" },
                  { title: "Conversion Rate", description: "Turning website visitors into booked patients.", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/woman-working-as-dentist-with-green-screen-monitor_482257-21568.jpg" },
                  { title: "Clinic Marketing", description: "Patient acquisition strategies that deliver results.", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/beautiful-girl-sitting-dentist-s-office_1157-28571.jpg" },
                  { title: "Full Maintenance", description: "Ongoing security, hosting, and performance optimization.", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/front-view-young-pretty-female-smiling-pink-background_179666-26612.jpg" }
                ]}
                textAnimation="fade-blur"
              />
            </SectionErrorBoundary>
          </div>
  );
}
