// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialMarqueeCards from '@/components/sections/testimonial/TestimonialMarqueeCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
            <SectionErrorBoundary name="testimonials">
              <TestimonialMarqueeCards
                tag="CLIENT TRUST"
                title="Voices of Excellence"
                description="Hear what successful dental practices have to say about working with us."
                testimonials={[
                  { name: "Dr. Sarah Miller", role: "Clinic Owner", quote: "DentaPro completely transformed our online identity. Our bookings doubled within 3 months.", imageSrc: "http://img.b2bpic.net/free-photo/closeup-happy-middle-aged-woman-leaning-wall_1262-1743.jpg" },
                  { name: "Dr. James Chen", role: "Orthodontist", quote: "Professional, efficient, and truly understood the luxury aesthetic I needed.", imageSrc: "http://img.b2bpic.net/free-photo/portrait-dentist-standing-clinic_107420-65271.jpg" },
                  { name: "Dr. Elena Rodriguez", role: "Cosmetic Specialist", quote: "The conversion rate optimization has been a game changer for our new patient influx.", imageSrc: "http://img.b2bpic.net/free-photo/pretty-young-woman-leaning-sofa_1262-3274.jpg" },
                  { name: "Dr. Mark Stevens", role: "Oral Surgeon", quote: "Highest quality work I have seen in this industry. Highly recommended.", imageSrc: "http://img.b2bpic.net/free-photo/woman-getting-treatment-hairdresser-shop_23-2149230932.jpg" },
                  { name: "Dr. Lisa Wong", role: "Pediatric Dentist", quote: "Stunning design, seamless process. They made everything so easy for our team.", imageSrc: "http://img.b2bpic.net/free-photo/closeup-smiling-adult-woman-leaning-wall_1262-1759.jpg" }
                ]}
                textAnimation="fade-blur"
              />
            </SectionErrorBoundary>
          </div>
  );
}
